name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.5
  material: ^1.0.0+2
  firebase_core: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 600

  assets:
    - assets/images/Get_started/get_started.png
    - assets/images/Get_started/get.png
    - assets/images/Tutorials/Tutorial_1.png
    - assets/images/Tutorials/Tutorial_1_1.png
    - assets/images/Tutorials/Tutorial_2.png
    - assets/images/Tutorials/Tutorial_1_2.png
    - assets/images/Tutorials/Tutorial_3.png
    - assets/images/Tutorials/Tutorial_1_3.png
    - assets/images/chflgn/Image2183.png
    - assets/images/chflgn/vector.svg
    - assets/images/login/Image2183.png
    - assets/images/otp/foood.png
    - assets/images/otp/31148832.png
    - assets/images/icons/salt.png
    - assets/images/icons/chicken.png
    - assets/images/icons/onion.png
    - assets/images/icons/garlic.png
    - assets/images/icons/peppers.png
    - assets/images/icons/ginger.png
    - assets/images/icons/avocado.png
    - assets/images/icons/apple.png
    - assets/images/icons/blueberry.png
    - assets/images/icons/broccoli.png
    - assets/images/icons/orange.png
    - assets/images/icons/walnut.png
    - assets/images/icons/food.jpg
    - assets/images/restr/chef.jpg
    - assets/images/restr/dum_biryani.jpg
    - assets/images/restr/hyderabadi_biryani.jpg
    - assets/images/signup/rectangle1575.svg
    - assets/images/signup/Freecookingfoodillustrationfreedownloadfooddrinkillustrationsiconscout1.png  
    - assets/images/signup/31148832.png


 
